### ISSUE TITLE
Item duplication glitch with Quark Oddities backpack

### ISSUE THREAD

**Issue by copygirl** [blay09/InventoryEssentials#10]
### Minecraft Version

1.18.x

### Mod Loader

Forge

### Mod Loader Version

40.1.68

### Mod Version

4.0.2

### Describe the Issue

When ctrl-clicking on a stack in a backpack from [Quark Oddities](https://www.curseforge.com/minecraft/mc-mods/quark-oddities) to move a single item into my inventory, it clones the entire stack into the target inventory, though reduces the original stack's amount as expected.

### Before

![image](https://user-images.githubusercontent.com/272586/183011477-92101cd2-a0e2-415a-a134-95a8c5e6b968.png)

### After

![image](https://user-images.githubusercontent.com/272586/183011643-67306b54-39db-4058-92a3-459f7b51c3c3.png)

### Do you use any performance-enhancing mods (e.g. OptiFine)?

FerriteCore, Radium Reforged, Rubidium

**Comment by Technici4n** [comment]
The same issue arises with Modern Industrialization. For reference, this is the slot class I'm using: https://github.com/AztechMC/Modern-Industrialization/blob/master/src/main/java/aztech/modern_industrialization/inventory/HackySlot.java.
