### ISSUE TITLE
Requesting additional function of alt+click from inventory to drop selected item/stack.

### ISSUE THREAD

**Issue by Matakor** [blay09/InventoryEssentials#16]
Inventorytweaks had this function, and I can't find any mods to add this specific function. Hoping it can be added to 1.19.2 specifically, as that's what's in the pack I'm playing, but it'd be nice to see it added either way.

**Comment by BlayTheNinth** [comment]
Ctrl + Q in Vanilla already provides this function. Configurable key bindings are planned in #11
