### ISSUE TITLE
Weird inventory mix when Space+Click

### ISSUE THREAD

**Issue by drakray** [blay09/InventoryEssentials#18]
### Minecraft Version

1.20.x

### Mod Loader

Forge

### Mod Loader Version

47.0.3

### Mod Version

8.0.0

### Balm Version

7.0.3

### Describe the Issue

Holding [Space] to click and transfer from chest to playerInventory completely mix everything in inventory

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

Oculus/Rubidium?, JEI, some other mods

**Comment by BlayTheNinth** [comment]
Need logs for a full list of mods. Is this on singleplayer or multiplayer? With mod installed on server or not?

**Comment by drakray** [comment]
![client list](https://github.com/TwelveIterationMods/InventoryEssentials/assets/4303126/aee85de4-9c70-4fd7-991f-1e0e4d6b84ed)
![server list](https://github.com/TwelveIterationMods/InventoryEssentials/assets/4303126/a724445c-c1f9-493f-9cd0-7a6e21b5021d)
Lastest.log https://pastebin.com/4BcuDiDt
Debug.log https://pastebin.com/tiA0CuB1

Happens on Solo and Server play
Mod is installed on both

**Comment by drakray** [comment]
upon further testing, it seems that Space-Click from chest to playerInventory invert the order of stuff, but not player2chest
might be related?
