### ISSUE TITLE
8.2.1 Breaks my Left Click

### ISSUE THREAD

**Issue by GabbyDG2805** [blay09/InventoryEssentials#20]
### Minecraft Version

1.20.x

### Mod Loader

Fabric

### Mod Loader Version

0.14.22

### Mod Version

8.2.1

### Balm Version

7.1.2

### Describe the Issue

Today I updated from version 8.1.0 to 8.2.1 and Balm from version 7.0.7 to 7.1.2 and now my left click no longer works if I have this mod installed, it doesn't do anything. Balm and other balm-dependent mods seem fine, its just this mod. I usually have this button set to place block so I can't place blocks but if I change back to the default of right click to place and left click to attack, I can no longer attack. So whatever my left click is bound to just doesn't work.

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

Sodium

**Comment by BlayTheNinth** [comment]
Should be fixed in Balm 7.1.3
