### ISSUE TITLE
Key binds for inventory navigation

### ISSUE THREAD

**Issue by Clozent** [blay09/InventoryEssentials#22]
A great feature to add is (configurable) key binds for navigating the inventory.
For example, I could use the arrow keys to move around in the inventory and use additional key binds to pick up and move all the items in that slot, send them all to a chest with a different, spread them in an inventory space by pressing a button and moving with the arrow keys, etc..

In the creative menu, it would also scroll down/up automatically when the selection reaches a certain (configurable?) height threshold.

The main selling point of this feature is that players could actually use remapped controllers for playing the game, since having to move the mouse cursor in the inventory with a controller feels awful. Instead they could remap the D-pad to use for inventory navigation.

**Comment by BlayTheNinth** [comment]
This seems to be better suited for a mod like [Controllable](https://www.curseforge.com/minecraft/mc-mods/controllable).

**Comment by Clozent** [comment]
Controllable doesn't really have good controller support (from my experience, at least), and besides, that feature would be useful beyond just controller mapping (such as using the keyboard to navigate inventories).
