### ISSUE TITLE
Shift + Drag does not function on the Survival Inventory page while in Creative Mode.

### ISSUE THREAD

**Issue by rishagamer** [blay09/InventoryEssentials#23]
### Minecraft Version

1.20.1 (LTS)

### Mod Loader

Forge

### Mod Loader Version

47.1.79

### Mod Version

8.2.1

### Balm Version

7.1.4

### Describe the Issue

Loaded into a fresh world with Inventory Sorter installed. Switched to creative to avoid server trying to kill me by spawning in water. Opened creative inventory, moved to survival tab, and did a shift+drag to move books from Ars Nouveau, Simply Swords, and Alex's Mobs from my bar to my inventory. Expected items to move up, but items did not move. Shift-clicking only seems to work directly on the item. But ONLY on that inventory page in creative mode.

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

Currently running on NeoForge 1.20.1-47.1.79 for Minecraft 1.20.1

**Comment by peow** [comment]
im using the newest InventoryEssential version (8.2.3) in **Fabric 1.20.1** and this is still happening


https://github.com/TwelveIterationMods/InventoryEssentials/assets/105888751/e054b208-9248-411e-b731-797b61064edf

*im holding SHIFT all the time*


latest.log: https://mclo.gs/8cXXXjn
