### ISSUE TITLE
Crash when dragging multiple stacks from hotbar into creative inventory

### ISSUE THREAD

**Issue by Amp63** [blay09/InventoryEssentials#29]
### Minecraft Version

Other (specify below)

### Mod Loader

Fabric

### Mod Loader Version

0.15.6

### Mod Version

9.0.1

### Balm Version

8.0.5

### Describe the Issue

Playing 1.20.2, game crashes when I shift click and drag across my hotbar while in a creative inventory menu to delete the items

Reproduction:
1. Open a world in creative mode
2. Fill hotbar with items
3. Open creative inventory, go to a page with items like "Building Blocks"
4. Shift left click and drag across hotbar

Expected Result: Items are deleted
Actual Result: Game crash

### Logs

https://pastebin.com/w4rBmW7z

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

None

**Comment by BlayTheNinth** [comment]
1.20.2 is no longer supported. Currently, only 1.20.1 and 1.20.4 are receiving updates.

**Comment by Amp63** [comment]
Ah, should have checked for that. Thanks!
