### ISSUE TITLE
Not working property on minecraft 1.20.1  with mod version above 8.1.0

### ISSUE THREAD

**Issue by wilebaldo** [blay09/InventoryEssentials#31]
I have problems with the mod if I install version above 8.1.0 this is the last version is working fine with Minecraft 1.20.1

And the principal function I used with this mod is moving from a chest to my inventory a single item pressing the key (alt) + Click on the stack of the item and with this is moved a single item to my inventory with every click I do. and is not working

**Comment by BlayTheNinth** [comment]
The key for a single item move is CTRL, not ALT. 

8.1.0 made the keys configurable, so maybe you have unbound the Single Item Transfer key in the Controls menu.

**Comment by wilebaldo** [comment]
> The key for a single item move is CTRL, not ALT.
> 
> 8.1.0 made the keys configurable, so maybe you have unbound the Single Item Transfer key in the Controls menu.

Well, I'm playing on a Mac and my keyboard is a windows, so I'm not sure about what the correct key is binded, but I'm using the key ALT is next to the bar space, and I don't make any change on the keys used on this mod.

But anyway, when I install the mod version 8.1.0 everything is working ok, but as soon I upgraded the version of the mod I got problems.

![Screenshot 2024-03-20 at 23 26 37](https://github.com/TwelveIterationMods/InventoryEssentials/assets/8034131/975a157d-a1cf-4556-a7e4-40f39dedd714)

**Comment by BlayTheNinth** [comment]
Check Minecraft's Controls menu, not the mod configuration.

**Comment by wilebaldo** [comment]
I checked all the configurations on the minecraft and I don't found anything else to change the keys for this MOD. The case is in the version 8.1.0 is working ok, but in any version higher is not working on minecraft 1.20.1. Soon I will upgrade to 1.20.4 I will let you know if the problem persist on that version.

![Screenshot 2024-03-23 at 13 07 17](https://github.com/TwelveIterationMods/InventoryEssentials/assets/8034131/282136d3-ab98-4da6-95db-fe4f9c1bf81a)
![Screenshot 2024-03-23 at 13 09 33](https://github.com/TwelveIterationMods/InventoryEssentials/assets/8034131/34a76f76-7d43-4465-83cf-d4db6e3ea089)

**Comment by BlayTheNinth** [comment]
Closing since the key is configurable in newer versions and the fact that ALT stopped working on Mac is only because it was always supposed to be CTRL and is now handled properly through Minecraft's keybindings.
