### ISSUE TITLE
game crashes on shift clicking items with another item held in mouse ("Index (n) out of bounds for length 46")

### ISSUE THREAD

**Issue by NoIDidntHackU** [blay09/InventoryEssentials#33]
### Minecraft Version

1.20.4

### Mod Loader

Fabric

### Mod Loader Version

0.15.3

### Mod Version

10.0.1

### Balm Version

9.0.4

### Describe the Issue

game crashes on shift clicking items with another item held in mouse ("Index (n) out of bounds for length 46")

### Logs

https://mclo.gs/IkgoPRG

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

sodium, nvidium, sodium extra, iris, indium, prism

**Comment by BlayTheNinth** [comment]
I can't reproduce this issue. Please provide a step-by-step guide on how to make the problem appear.

**Comment by NoIDidntHackU** [comment]
I also have another mod called mouse tweaks installed, removing that one or this one fixed the issue

**Comment by NoIDidntHackU** [comment]
I forgot to close this thread
