### ISSUE TITLE
[1.16.5] Ctrl-clicking recipe output voids blocks in multi-output recipes

### ISSUE THREAD

**Issue by NielsPilgaard** [blay09/InventoryEssentials#4]
Reproduced and relayed from https://github.com/NillerMedDild/Enigmatica6/issues/1864

> When crafting from multiple stacks and holding ctrl while clicking on output to get the whole lot, it yields only half of single craft output. I.e:
> 
> ![image](https://user-images.githubusercontent.com/10334982/113001985-462ed500-9169-11eb-994e-ecbbd29e9bc6.png)
> when ctrl+clicked should deploy 8 stairs to my inventory, instead I'm getting just 2, but it takes all the crafting resources and vanishes it.

**Comment by FenixR** [comment]
Can confirm, this bug recently happened to me making sticks and torches. If you are holding an item though it will sometimes craft correctly, and sometimes leave the leftover items in the result window (as in, it craft 4 sticks, places 1 in inventory, leave the other 3 in the result window). Already tested with no mods handling inventory besides this one.
