### ISSUE TITLE
Incompatibility with 'sophisticatedbackpacks'

### ISSUE THREAD

**Issue by 2929762171** [blay09/InventoryEssentials#40]
### Minecraft Version

Other (specify below)

### Mod Loader

Forge

### Mod Loader Version

43.3.7

### Mod Version

inventoryessentials-forge-1.19.2-5.4.0

### Balm Version

balm-forge-1.19.2-4.6.0

### Describe the Issue

Items after 'no sort slot' can't be moved with 'ctrl+click'. sometimes the front side items can't move too (p3), that was the first time I encountered this problem.
![image](https://github.com/user-attachments/assets/65c6dbd8-47f5-4d08-8721-246f74e6dfd2)
![image](https://github.com/user-attachments/assets/634e4117-a431-42e6-b2c9-f08315a94c54)
![image](https://github.com/user-attachments/assets/eb089d9a-2da1-4ad6-952e-78e7d8afc686)

### Logs

.

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

no

**Comment by 2929762171** [comment]
btw, item in the front side can't be moved seems only occurs on the server (server didn't have this mod).

**Comment by BlayTheNinth** [comment]
As discovered in https://github.com/TwelveIterationMods/TrashSlot/issues/131, Sophisticated Backpacks deviate a lot from Vanilla expectations of containers. Unfortunately, proper support for them is unfeasible.
