### ISSUE TITLE
Mod key binds are not present in Options > Controls > Key binds

### ISSUE THREAD

**Issue by ephilippo** [blay09/InventoryEssentials#41]
### Minecraft Version

1.21

### Mod Loader

Fabric

### Mod Loader Version

0.16.0

### Mod Version

21.0.2

### Balm Version

21.0.14

### Describe the Issue

Despite the message in ModMenu settings, controls for this mod are not present in the Vanilla key binds menu.  In addition, nothing new appears to be written to my `options.txt`.

#### Minimally reproducible modlist

- Balm
- Cloth Config 15.0.128
- Fabric API 0.100.7+1.21
- Inventory Essentials
- Mod Menu 11.0.1

#### Steps to reproduce

1. Install the specified version of Minecraft, Fabric, Balm, and this mod
2. Launch the game
3. Confirm via Mod Menu that this mod is installed
4. Navigate to _Options > Controls > Key binds_
5. Note no options are present for this mod under Inventory, Miscellaneous, or a custom heading

### Logs

https://pastebin.com/SjSdSseH

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

No.

**Comment by BlayTheNinth** [comment]
Keybinds are no longer configurable on Fabric for the time being due to technical limitations. The outdated config comment has been removed.
