### ISSUE TITLE
Holding shift while moving the mouse doesn't take items from Sophisticated Backpacks

### ISSUE THREAD

**Issue by ocram9** [blay09/InventoryEssentials#44]
### Security Notice

- [X] Users might post VIRUS LINKS in comment responses to issue reports. **DO NOT DOWNLOAD ANY FILES FROM HERE.**

### Minecraft Version

1.20.1 (LTS)

### Mod Loader

Forge

### Mod Loader Version

47.2.20

### Mod Version

8.2.6

### Balm Version

7.3.9

### Describe the Issue

When holding shift while moving the mouse it doesn't move the items from a backpack from Sophisticated Backpacks to the inventory. You can input items from the inventory while shift moving but you can't take them out without clicking each individual item (like vanilla).

### Logs

https://gist.github.com/ocram9/e160c93b3bf3395e7c53a4365a9e0785

**Comment by BlayTheNinth** [comment]
As discovered in https://github.com/TwelveIterationMods/TrashSlot/issues/131, Sophisticated Backpacks deviate a lot from Vanilla expectations of containers. Unfortunately, proper support for them is unfeasible.
