### ISSUE TITLE
Inventory Essentials crashes client when used with Bundle Inventory

### ISSUE THREAD

**Issue by AllOutJay** [blay09/InventoryEssentials#45]
### Minecraft Version

Other (specify below)

### Mod Loader

Fabric

### Mod Version

21.4.1

## **Information**
Minecraft version: 1.21.4
Modloader: Fabric
Fabric loader version: 0.16.9

Mod name: Inventory Essentials
Mod version: inventoryessentials-fabric-1.21.4-21.4.1.jar

Mod name: Bundle Inventory
Mod version: BundleInventory-Fabric-1.6.0.jar

## **Description**
The client crashes when using just Fabric API, Inventory Essentials, and Bundle Inventory. It happens when I am accessing the [Bundle Inventory](https://modrinth.com/mod/bundle-inventory) and then shifting click items out of it.

fyi: I raised a bug with Bundle Inventory too https://legacy.curseforge.com/minecraft/mc-mods/bundle-inventory/issues/1

## **Crash report**
[crash.txt](https://mclo.gs/Xnf0zFA)

### Logs

https://mclo.gs/Xnf0zFA

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge or Arclight)?

Happens with just Fabric API, Inventory Essentials, and Bundle Inventory

**Comment by BlayTheNinth** [comment]
I don't think this is an issue in Inventory Essentials, since it checks if the slot is within bounds before performing the click and so this crash shouldn't be possible under normal circumstances.

**Comment by AllOutJay** [comment]
@BlayTheNinth the author of the other mod appears to be on it now. Not really sure who would/should fix it in the end.

**Comment by AllOutJay** [comment]
@BlayTheNinth Bundle Inventory added support on their end per https://legacy.curseforge.com/minecraft/mc-mods/bundle-inventory/issues/1 will be closing!
