### ISSUE TITLE
The shift-drag function does not work

### ISSUE THREAD

**Issue by ODS53A** [blay09/InventoryEssentials#5]
### Minecraft Version

1.17

### Mod Loader

Fabric

### Mod Loader Version

0.11.6

### Mod Version

3.0.0

### Describe the Issue

All the other functions appear to work, but when I try to shift-drag stacks, it only transfers the first stack where I clicked and started dragging.

### Do you use any performance-enhancing mods (e.g. OptiFine)?

I do have Optifine w/ optifabric but it still doesn't work with them removed

**Comment by BlayTheNinth** [comment]
Does this still happen on 1.18 with latest Balm? I've just tried with only Inventory Essentials (+ dependencies) and it's working fine for me.
